# Generated by Django 3.0.7 on 2020-06-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouterDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dns_records', models.CharField(max_length=255)),
                ('internet_host_names', models.CharField(max_length=255)),
                ('client_ip_address', models.CharField(max_length=255)),
                ('mac_address', models.CharField(max_length=255)),
            ],
        ),
    ]
