# Generated by Django 3.0.3 on 2020-06-05 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routerDetails', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RouterDetails',
            new_name='RouterDetail',
        ),
    ]
