# Generated by Django 3.0.7 on 2020-06-06 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routerDetails', '0002_auto_20200605_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routerdetail',
            old_name='client_ip_address',
            new_name='loopback',
        ),
        migrations.RenameField(
            model_name='routerdetail',
            old_name='dns_records',
            new_name='sap_id',
        ),
    ]
