# Generated by Django 3.0.7 on 2020-06-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerDetails', '0003_auto_20200606_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerdetail',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
