# Generated by Django 2.1.7 on 2020-09-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerDetails', '0004_routerdetail_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerdetail',
            name='loopback',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='routerdetail',
            name='sap_id',
            field=models.CharField(choices=[('AGI1', 'AG1'), ('CSS', 'CSS')], default='AGI1', max_length=6),
        ),
        migrations.AlterUniqueTogether(
            name='routerdetail',
            unique_together={('internet_host_names', 'loopback')},
        ),
    ]
